language: php

php:
    - 5.5
    - 5.4

env:
    - DB=mysql

before_script:
    - composer self-update
    - composer install
    - mysql -e 'CREATE DATABASE itc_test'
    - mysql -e "GRANT ALL PRIVILEGES ON *.* TO root@localhost IDENTIFIED BY 'root' WITH GRANT OPTION;"
    - mysql itc_test < data/fixture/itc.schema
    - cp data/config/database.ini.orig data/config/database.ini
    - cp data/config/aws.ini.orig data/config/aws.ini

script:
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php bin/coveralls -v -c .coveralls.yml

notifications:
    email:
        - app2641@gmail.com
    on_success: always
    on_failure: always

