language: php

php:
    - 5.5
    - 5.4

env:
    - DB=mysql

before_script:
    - composer self-update
    - composer install
    - mysql -e 'CREATE DATABASE itc_test'
    - mysql itc_test < data/fixture/itc.schema

script:
    - phpunit

notifications:
    email:
        - app2641@gmail.com
    on_success: always
    on_failure: always

