language: php

php:
    - 5.5
    - 5.4

before_script:
    - composer install

script:
    - phpunit

notifications:
    email:
        - app2641@gmail.com
    on_success: always
    on_failure: always

